FROM grafana/grafana:latest

USER root

# Certifique-se de que todos os diretórios de provisionamento existem antes de copiá-los

RUN mkdir -p /var/lib/grafana/dashboards
# Copiar os arquivos para o diretório correto
COPY provisioning/datasource.yml /etc/grafana/provisioning/datasources/
COPY provisioning/dashboard.yml /etc/grafana/provisioning/dashboards/
COPY dashboards/mariadb_dashboard.json /var/lib/grafana/dashboards/

# Garantir permissões para o usuário grafana
RUN chown -R 472:472 /etc/grafana/provisioning /var/lib/grafana/dashboards

USER grafana