# Dockerfile (Flask AppBuilder)
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Adiciona as dependências de teste
RUN pip install --no-cache-dir pytest pytest-mock

COPY tests/ /app/tests/

COPY app.py /app/

CMD ["flask", "run", "--host=0.0.0.0"]
